version: "3.9"

services:
  db:
    image: postgres
    container_name: beehive_db
    restart: always
    env_file:
      - config/.env
    ports:
      - 5432:5432
    volumes:
      - .dbdata:/var/lib/postgresql

  redis:
    image: redis:alpine
    container_name: beehive_redis
    ports:
      - 6379:6379

  web:
    build: .
    container_name: beehive_web
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - config/.env
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis