version: "3.9"

services:
  db:
    image: postgres
    container_name: beehive_db
    restart: always
    environment:
      POSTGRES_DB: beehive_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bernardoreyes
    ports:
      - 5432:5432
    volumes:
      - .data:/var/lib/postgresql

  redis:
    image: redis
    container_name: beehive_redis
    ports:
      - 6379:6379

  web:
    container_name: beehive_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis