name: Beehive CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Lint with flake8
        run: |
          pip install flake8 pytest
          flake8
          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Coverage report
        run: |
          pip install coverage
          coverage run manage.py test
          coverage report

      - name: Django testing
        run: |
          python manage.py test
